name: Discord Notification

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - closed

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord embed
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "embeds": [
              {
                "title": "🎮 Morgames Development",
                "description": "Pull Request aggiornamento",
                "color": 5793266,
                "fields": [
                  {
                    "name": "📌 Titolo",
                    "value": "${{ github.event.pull_request.title }}"
                  },
                  {
                    "name": "👤 Autore",
                    "value": "${{ github.event.pull_request.user.login }}"
                  },
                  {
                    "name": "🔗 Link",
                    "value": "${{ github.event.pull_request.html_url }}"
                  }
                ],
                "footer": {
                  "text": "Morgames GitHub"
                }
              }
            ]
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}